on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 12 * *"

name: check-links

jobs:
  check-links:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Remove lines with false positives
        run: |
          sed -i 's/.*check_links.yaml.*//g' README.md
          sed -i 's/.*check_spelling.yaml.*//g' README.md

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
